language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

env:
  global:
  - secure: Hc1TXd8d086olF4wpAnQVHIPMXyyQLxTAER80f4SLN8YpwAHx7sexSK3xzZRY/ILNmLdhBax6nejZzA6ybgSFj/9wYOrP68tU4/VmAt0r9BZmcobPxsqxYPi4moPny/KKXAPVQ2HcYGQfwQ9K4B3GTXgmd5jjXuUc8f3XOPCqabx4H3SyzZDMn9QoOGTYy6ka2b6d3+zGr0ZgSBf1qqOkIkfdJYCu2DDBedysKHI8EsLxEA/RoKRrSna5EiFE+VV6yd8sPhx0hZt/wfTD+VqYJ3T1zFfHR7Y6BqU29k7PonMd9ZAugFTMLexKIzo06jPzPLdvSaDmi79+rmKLmuTJgDvoUJ88v0vwmKwdIwEVYm/jtvuA8ox4B38+eCxZEVphOBg7AUXvMHg7/ik2p5bRfwkShPchg7tOJ0jHKte+rs//veovItJ4Se24K/vDtpKkY0KLqIotIo3eiRqqy146C14PsSlbr1FU735aovsBQL4CfocHeBhwUDlWkMHYWv+jtdxD9t4D8yxVHS/RKNxRC8rRXrsNQU5SpSpeCCOwwvG2Gr86SKqw4/G7fNQLkYyySBWnV/xW6sQG/3mcJvD44P+ltGMdaUMXPItE3g8GWisq0CZkJX3kI5Zcf8WsbIZ3XbjDu1A/AhvGNFPbwoVTFpX5leKmuNAwGeRoXUZxdI=
  - secure: k6B+Zt2LA2OWM/eQdqwlgoEtrmJgAnRxUamWkbZFwOBLsKOM+CFakmR7AQ4LAd+yvHzgCvYpRIcR6c4IHWBS6mHSgQzOqFZ+ipIO0/4kdIZb0nCC3F0So93tjt46hZtyxor2RjWZ7fxc78FlIbPAH+izO9TXVTyP3H4tCD50ZY8jrln2Bi8Wwtn113ttBCuZu7OsP+2CzH+Msugbgtr+c7NlHi3Wv3SFv8gBRfwwzRdK8a7uDY2uX+3P2Gp01s6zoWRalHBr7bLzrzpIF6C4ujj3NTl98wWNkNHzY53LYiC0QMfe8b674VGQY+klY7m13bMO8caVvOIejF8NzquWKzSVP5J5YPFGusjeGNALXU9a5yzrElXRiibJMe/+oYu5E8KNWSHXTSzGeFafLFMsGXrnmUHJ2qeUj0+Jpw09OzIO89KLltb/YGmh4wSLY43Ltx19aF4Udve0BXz0ZEvZJOGAuZej3mi4YOjjRbGwJg0ofAYHTfzZ36Is1E/zqRqyPuG+PrXqb/HxF/b/bdjDBnuURLpJvWd2pniQRWiwhxy/4JDcWF7ZkgM7pG4DjFLg107bhx4D2LBE/6ULMzB0VkNALhzP0+QTw/Ki7CjI86xkPHll9EtOmAPJ4GDvsOj0FgpDwzbBE2Or9Cfuf29YzEN3LxzZFEonw7xN7olR/Oc=

after_success:
  - '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
